In [9]:
import numpy as np
import pandas as pd

In [10]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [16]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [14]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [17]:
movies.shape

(4803, 20)

In [18]:
credits.shape

(4803, 4)

In [20]:
movies = movies.merge(credits, on='title')

In [21]:
movies.shape

(4809, 23)

In [23]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [26]:
# genres
# id
# keywords
# title
# overview
# cast
# crew - directors
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [30]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [31]:
movies.dropna(inplace=True)

In [32]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [43]:
movies.duplicated().sum()

0

In [44]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [49]:
# genre place in 1 format
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [50]:
movies['genres'] = movies['genres'].apply(convert)

In [51]:
movies_genres

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [52]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [54]:
movies['keywords'] = movies['keywords'].apply(convert)

In [55]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [56]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4806, dtype: object

In [59]:
# cast place in 1 format
import ast
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter = counter+1
        else:
            break
    return L

In [60]:
movies['cast'] = movies['cast'].apply(convert3)

In [61]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [64]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [65]:
# crew place in 1 format
import ast
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break            
    return L

In [67]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [68]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [70]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [72]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [73]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [76]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [77]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [78]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [79]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [80]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [81]:
new_df = movies[['movie_id', 'title', 'tags']]

In [82]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [84]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\pc\AppData\Local\Temp\ipykernel_9076\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [85]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [87]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\pc\AppData\Local\Temp\ipykernel_9076\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [88]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [89]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [90]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

# Text Vectorization

Text vectorization is the broad process of converting words, sentences, or entire documents into numbers that machine learning models can work with. It’s like creating a translation dictionary between human language and computer language.

In [101]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [102]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [103]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [106]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [107]:
import nltk

In [109]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [111]:
ps.stem('loving')

'love'

In [112]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [114]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\pc\AppData\Local\Temp\ipykernel_9076\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [115]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [116]:
from sklearn.metrics.pairwise import cosine_similarity

In [121]:
similarity = cosine_similarity(vectors)

In [122]:
similarity[2]

array([0.05976143, 0.0625    , 1.        , ..., 0.02635231, 0.        ,
       0.        ])

In [123]:
similarity[0]

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ])

In [132]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.08964214570007951),
 (2, 0.059761430466719674),
 (3, 0.03984095364447979),
 (4, 0.1825741858350554),
 (5, 0.1183452670827877),
 (6, 0.02258769757263128),
 (7, 0.1763834207376394),
 (8, 0.061721339984836754),
 (9, 0.07644707871564382),
 (10, 0.11769797726729994),
 (11, 0.081199794294115),
 (12, 0.09583148474999097),
 (13, 0.04733810683311508),
 (14, 0.11428571428571427),
 (15, 0.05096471914376255),
 (16, 0.08226127456606226),
 (17, 0.15026857675938213),
 (18, 0.1129384878631564),
 (19, 0.08728715609439694),
 (20, 0.058167505074711086),
 (21, 0.09583148474999097),
 (22, 0.07049073768502413),
 (23, 0.09583148474999097),
 (24, 0.0563436169819011),
 (25, 0.036454130828824455),
 (26, 0.17142857142857143),
 (27, 0.18935242733246033),
 (28, 0.12555296411486888),
 (29, 0.07100716024967263),
 (30, 0.07319250547113999),
 (31, 0.16265001215808886),
 (32, 0.09116846116771035),
 (33, 0.10350983390135313),
 (34, 0.0),
 (35, 0.10350983390135313),
 (36, 0.18478728707195913),
 (37, 0.08451542547285165),
 (38, 0.0628970902033151),
 (39, 0.08827348295047496),
 (40, 0.0563436169819011),
 (41, 0.14638501094227999),
 (42, 0.0),
 (43, 0.09759000729485333),
 (44, 0.03984095364447979),
 (45, 0.09116846116771035),
 (46, 0.1765469659009499),
 (47, 0.2164218276749025),
 (48, 0.06776309271789384),
 (49, 0.06388765649999398),
 (50, 0.12143534814378325),
 (51, 0.086568731069961),
 (52, 0.1389425035941821),
 (53, 0.04984447862792268),
 (54, 0.035245368842512066),
 (55, 0.07859774918918593),
 (56, 0.14414999403128942),
 (57, 0.028988551782622416),
 (58, 0.04688072309384954),
 (59, 0.08024108542850393),
 (60, 0.028571428571428567),
 (61, 0.22131333406899523),
 (62, 0.08199200616907877),
 (63, 0.09200874124564722),
 (64, 0.03138824102871722),
 (65, 0.020965696734438367),
 (66, 0.02492223931396134),
 (67, 0.17928429140015903),
 (68, 0.13522468075656266),
 (69, 0.0520265981714472),
 (70, 0.08696565534786725),
 (71, 0.081199794294115),
 (72, 0.12344267996967351),
 (73, 0.03688555567816587),
 (74, 0.22677868380553634),
 (75, 0.09107651110783743),
 (76, 0.07733088933397005),
 (77, 0.014824986333222025),
 (78, 0.0515539262226467),
 (79, 0.0791945516022682),
 (80, 0.03450327796711771),
 (81, 0.11710800875382396),
 (82, 0.08336550215650926),
 (83, 0.22190115272469205),
 (84, 0.1456438162508838),
 (85, 0.10631548679075009),
 (86, 0.08827348295047496),
 (87, 0.11595420713048966),
 (88, 0.09107651110783743),
 (89, 0.06121333677828399),
 (90, 0.06506000486323554),
 (91, 0.15971914124998493),
 (92, 0.0703210846407743),
 (93, 0.05096471914376255),
 (94, 0.16574838603294897),
 (95, 0.12461119656980668),
 (96, 0.08964214570007951),
 (97, 0.07476671794188401),
 (98, 0.09107651110783743),
 (99, 0.029424494316824985),
 (100, 0.07377111135633174),
 (101, 0.08827348295047496),
 (102, 0.11194341570991125),
 (103, 0.0880237696271323),
 (104, 0.059761430466719674),
 (105, 0.10811249552346706),
 (106, 0.0447773662839645),
 (107, 0.09200874124564722),
 (108, 0.16903085094570328),
 (109, 0.07968190728895957),
 (110, 0.024655683636076894),
 (111, 0.15179418517972906),
 (112, 0.09258200997725513),
 (113, 0.052164053095730106),
 (114, 0.0515539262226467),
 (115, 0.055577001437672836),
 (116, 0.057142857142857134),
 (117, 0.060717674071891624),
 (118, 0.017622684421256033),
 (119, 0.04829452884162951),
 (120, 0.0),
 (121, 0.09107651110783743),
 (122, 0.09759000729485331),
 (123, 0.12327841818038447),
 (124, 0.06776309271789384),
 (125, 0.08021849185198157),
 (126, 0.11595420713048966),
 (127, 0.13662601021279464),
 (128, 0.0),
 (129, 0.10559273546969093),
 (130, 0.03194382824999699),
 (131, 0.1126872339638022),
 (132, 0.04733810683311508),
 (133, 0.033806170189140665),
 (134, 0.13522468075656266),
 (135, 0.0),
 (136, 0.025482359571881275),
 (137, 0.03450327796711771),
 (138, 0.08336550215650926),
 (139, 0.10910894511799617),
 (140, 0.05096471914376255),
 (141, 0.11633501014942217),
 (142, 0.0994490316197694),
 (143, 0.06965451903188581),
 (144, 0.055577001437672836),
 (145, 0.02258769757263128),
 (146, 0.017434201093860163),
 (147, 0.06277648205743444),
 (148, 0.1057361065275362),
 (149, 0.1717355162964367),
 (150, 0.1901597073139162),
 (151, 0.19920476822239894),
 (152, 0.06388765649999398),
 (153, 0.08586775814821836),
 (154, 0.033149677206589796),
 (155, 0.0),
 (156, 0.06716604942594674),
 (157, 0.1057361065275362),
 (158, 0.15289415743128765),
 (159, 0.06761234037828133),
 (160, 0.09569487529386908),
 (161, 0.035245368842512066),
 (162, 0.03688555567816587),
 (163, 0.052796367734845466),
 (164, 0.09258200997725513),
 (165, 0.05039526306789696),
 (166, 0.11952286093343935),
 (167, 0.06761234037828133),
 (168, 0.16035674514745463),
 (169, 0.11952286093343936),
 (170, 0.09200874124564722),
 (171, 0.029880715233359837),
 (172, 0.15118578920369088),
 (173, 0.02492223931396134),
 (174, 0.11115400287534567),
 (175, 0.0515539262226467),
 (176, 0.030860669992418377),
 (177, 0.0),
 (178, 0.02577696311132335),
 (179, 0.07755667343294811),
 (180, 0.023002185311411804),
 (181, 0.02344036154692477),
 (182, 0.10826639239215334),
 (183, 0.07466533929465573),
 (184, 0.1825741858350554),
 (185, 0.055577001437672836),
 (186, 0.04040610178208843),
 (187, 0.14085904245475275),
 (188, 0.022792115291927588),
 (189, 0.08199200616907877),
 (190, 0.08386278693775347),
 (191, 0.05096471914376255),
 (192, 0.0),
 (193, 0.0880237696271323),
 (194, 0.0),
 (195, 0.06506000486323554),
 (196, 0.05797710356524483),
 (197, 0.047809144373375745),
 (198, 0.059761430466719674),
 (199, 0.11609086505314302),
 (200, 0.07968190728895957),
 (201, 0.0),
 (202, 0.03450327796711771),
 (203, 0.08827348295047496),
 (204, 0.02577696311132335),
 (205, 0.07968190728895957),
 (206, 0.1183452670827877),
 (207, 0.0857142857142857),
 (208, 0.1690308509457033),
 (209, 0.03779644730092272),
 (210, 0.05484084971070818),
 (211, 0.027066598098038335),
 (212, 0.07644707871564382),
 (213, 0.06492654830247076),
 (214, 0.029880715233359837),
 (215, 0.07319250547113999),
 (216, 0.06506000486323554),
 (217, 0.045584230583855176),
 (218, 0.042257712736425826),
 (219, 0.06629935441317959),
 (220, 0.18832944617230335),
 (221, 0.024655683636076894),
 (222, 0.09035079029052512),
 (223, 0.08336550215650926),
 (224, 0.06338656910463875),
 (225, 0.052796367734845466),
 (226, 0.029880715233359837),
 (227, 0.09258200997725513),
 (228, 0.12741179785940637),
 (229, 0.07755667343294811),
 (230, 0.08322503785764788),
 (231, 0.0),
 (232, 0.11952286093343935),
 (233, 0.1057361065275362),
 (234, 0.06776309271789384),
 (235, 0.059761430466719674),
 (236, 0.09583148474999097),
 (237, 0.06900655593423542),
 (238, 0.12777531299998796),
 (239, 0.11097419040461878),
 (240, 0.05096471914376255),
 (241, 0.08964214570007951),
 (242, 0.09416472308615166),
 (243, 0.09968895725584535),
 (244, 0.06277648205743444),
 (245, 0.09107651110783743),
 (246, 0.06601782722034923),
 (247, 0.0),
 (248, 0.04733810683311508),
 (249, 0.14414999403128942),
 (250, 0.0),
 (251, 0.042257712736425826),
 (252, 0.022792115291927588),
 (253, 0.06776309271789384),
 (254, 0.08226127456606226),
 (255, 0.0),
 (256, 0.08199200616907877),
 (257, 0.0857142857142857),
 (258, 0.02344036154692477),
 (259, 0.06388765649999398),
 (260, 0.25110592822973776),
 (261, 0.025482359571881275),
 (262, 0.07319250547113999),
 (263, 0.1057361065275362),
 (264, 0.0),
 (265, 0.029424494316824985),
 (266, 0.11115400287534567),
 (267, 0.07207499701564471),
 (268, 0.02742042485535409),
 (269, 0.033149677206589796),
 (270, 0.1031078524452934),
 (271, 0.0791945516022682),
 (272, 0.030860669992418377),
 (273, 0.024147264420814756),
 (274, 0.08095109602454656),
 (275, 0.12555296411486888),
 (276, 0.06629935441317959),
 (277, 0.06601782722034923),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (280, 0.0),
 (281, 0.07319250547113999),
 (282, 0.030860669992418377),
 (283, 0.0),
 (284, 0.020348923188911988),
 (285, 0.022792115291927588),
 (286, 0.02258769757263128),
 (287, 0.02742042485535409),
 (288, 0.0),
 (289, 0.05039526306789696),
 (290, 0.06629935441317959),
 (291, 0.0563436169819011),
 (292, 0.10141851056742199),
 (293, 0.03194382824999699),
 (294, 0.11952286093343935),
 (295, 0.10968169942141635),
 (296, 0.041300810278220045),
 (297, 0.048795003647426664),
 (298, 0.0),
 (299, 0.041300810278220045),
 (300, 0.18478728707195913),
 (301, 0.1831403087002079),
 (302, 0.059761430466719674),
 (303, 0.028988551782622416),
 (304, 0.07207499701564471),
 (305, 0.19320245583349133),
 (306, 0.09416472308615166),
 (307, 0.10460520656316097),
 (308, 0.07049073768502413),
 (309, 0.06629935441317959),
 (310, 0.036244018814637485),
 (311, 0.1564921592871903),
 (312, 0.11115400287534567),
 (313, 0.07968190728895957),
 (314, 0.0),
 (315, 0.09107651110783743),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.07207499701564471),
 (320, 0.033806170189140665),
 (321, 0.0),
 (322, 0.22230800575069137),
 (323, 0.03253000243161777),
 (324, 0.026398183867422733),
 (325, 0.11338934190276817),
 (326, 0.059761430466719674),
 (327, 0.029424494316824985),
 (328, 0.0),
 (329, 0.08336550215650926),
 (330, 0.1126872339638022),
 (331, 0.04984447862792268),
 (332, 0.1449427589131121),
 (333, 0.030860669992418377),
 (334, 0.10690449676496976),
 (335, 0.055577001437672836),
 (336, 0.07377111135633174),
 (337, 0.024147264420814756),
 (338, 0.0),
 (339, 0.057142857142857134),
 (340, 0.052796367734845466),
 (341, 0.061721339984836754),
 (342, 0.13662601021279464),
 (343, 0.022792115291927588),
 (344, 0.03138824102871722),
 (345, 0.02366905341655754),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06761234037828133),
 (349, 0.09258200997725513),
 (350, 0.05484084971070818),
 (351, 0.0),
 (352, 0.029880715233359837),
 (353, 0.023904572186687872),
 (354, 0.0),
 (355, 0.03984095364447979),
 (356, 0.09107651110783743),
 (357, 0.0),
 (358, 0.06506000486323554),
 (359, 0.03450327796711771),
 (360, 0.0),
 (361, 0.057142857142857134),
 (362, 0.09759000729485331),
 (363, 0.09116846116771035),
 (364, 0.026082026547865053),
 (365, 0.081199794294115),
 (366, 0.059761430466719674),
 (367, 0.0),
 (368, 0.13522468075656266),
 (369, 0.09258200997725513),
 (370, 0.0563436169819011),
 (371, 0.1031078524452934),
 (372, 0.05345224838248488),
 (373, 0.17622684421256032),
 (374, 0.04401188481356615),
 (375, 0.0432843655349805),
 (376, 0.048795003647426664),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05345224838248487),
 (380, 0.02817180849095055),
 (381, 0.09035079029052512),
 (382, 0.0),
 (383, 0.0515539262226467),
 (384, 0.03253000243161777),
 (385, 0.0),
 (386, 0.023218173010628604),
 (387, 0.027066598098038335),
 (388, 0.0),
 (389, 0.0994490316197694),
 (390, 0.028571428571428567),
 (391, 0.061046769566735964),
 (392, 0.03138824102871722),
 (393, 0.0),
 (394, 0.026082026547865053),
 (395, 0.057142857142857134),
 (396, 0.02344036154692477),
 (397, 0.055577001437672836),
 (398, 0.0),
 (399, 0.02577696311132335),
 (400, 0.10350983390135313),
 (401, 0.03194382824999699),
 (402, 0.06277648205743444),
 (403, 0.1109741904046188),
 (404, 0.06761234037828133),
 (405, 0.030860669992418377),
 (406, 0.021821789023599235),
 (407, 0.02577696311132335),
 (408, 0.03688555567816587),
 (409, 0.0),
 (410, 0.10079052613579392),
 (411, 0.05797710356524483),
 (412, 0.1031078524452934),
 (413, 0.1389425035941821),
 (414, 0.033149677206589796),
 (415, 0.0708769911938334),
 (416, 0.0563436169819011),
 (417, 0.03450327796711771),
 (418, 0.03779644730092272),
 (419, 0.07644707871564382),
 (420, 0.12888481555661674),
 (421, 0.0),
 (422, 0.14754222271266348),
 (423, 0.0515539262226467),
 (424, 0.040697846377823976),
 (425, 0.07100716024967263),
 (426, 0.06195121541733006),
 (427, 0.030860669992418377),
 (428, 0.05976143046671968),
 (429, 0.0),
 (430, 0.052164053095730106),
 (431, 0.02577696311132335),
 (432, 0.12598815766974242),
 (433, 0.033149677206589796),
 (434, 0.0),
 (435, 0.03984095364447979),
 (436, 0.0),
 (437, 0.028988551782622416),
 (438, 0.028571428571428567),
 (439, 0.030860669992418377),
 (440, 0.028571428571428567),
 (441, 0.030358837035945812),
 (442, 0.04829452884162951),
 (443, 0.05884898863364997),
 (444, 0.0),
 (445, 0.028571428571428567),
 (446, 0.02577696311132335),
 (447, 0.023904572186687872),
 (448, 0.02577696311132335),
 (449, 0.05884898863364997),
 (450, 0.026398183867422733),
 (451, 0.026082026547865053),
 (452, 0.03194382824999699),
 (453, 0.02672612419124244),
 (454, 0.1246111965698067),
 (455, 0.024655683636076894),
 (456, 0.0703210846407743),
 (457, 0.08827348295047496),
 (458, 0.04733810683311508),
 (459, 0.036037498507822355),
 (460, 0.028571428571428567),
 (461, 0.18018749253911176),
 (462, 0.0),
 (463, 0.035245368842512066),
 (464, 0.0),
 (465, 0.0),
 (466, 0.2114722130550724),
 (467, 0.09200874124564722),
 (468, 0.030358837035945812),
 (469, 0.0703210846407743),
 (470, 0.04931136727215379),
 (471, 0.08336550215650926),
 (472, 0.08451542547285165),
 (473, 0.1019294382875251),
 (474, 0.0),
 (475, 0.06837634587578276),
 (476, 0.10811249552346706),
 (477, 0.0),
 (478, 0.04040610178208843),
 (479, 0.09508728264112047),
 (480, 0.052164053095730106),
 (481, 0.0),
 (482, 0.030358837035945812),
 (483, 0.1301200097264711),
 (484, 0.03450327796711771),
 (485, 0.057142857142857134),
 (486, 0.05855400437691198),
 (487, 0.14098147537004826),
 (488, 0.07655590023509526),
 (489, 0.0),
 (490, 0.15118578920369088),
 (491, 0.09116846116771035),
 (492, 0.06277648205743444),
 (493, 0.01951800145897066),
 (494, 0.0),
 (495, 0.2162249910469341),
 (496, 0.0),
 (497, 0.0),
 (498, 0.07207499701564471),
 (499, 0.0),
 (500, 0.027788500718836418),
 (501, 0.0880237696271323),
 (502, 0.15289415743128765),
 (503, 0.08451542547285165),
 (504, 0.0),
 (505, 0.14754222271266348),
 (506, 0.036037498507822355),
 (507, 0.25302403842552984),
 (508, 0.11595420713048966),
 (509, 0.02577696311132335),
 (510, 0.10559273546969093),
 (511, 0.09583148474999097),
 (512, 0.060717674071891624),
 (513, 0.11769797726729994),
 (514, 0.059761430466719674),
 (515, 0.027066598098038335),
 (516, 0.026082026547865053),
 (517, 0.0),
 (518, 0.05484084971070818),
 (519, 0.0),
 (520, 0.0),
 (521, 0.028988551782622416),
 (522, 0.0),
 (523, 0.052164053095730106),
 (524, 0.0),
 (525, 0.02492223931396134),
 (526, 0.0),
 (527, 0.0),
 (528, 0.02519763153394848),
 (529, 0.13041013273932528),
 (530, 0.10141851056742199),
 (531, 0.05039526306789696),
 (532, 0.023218173010628604),
 (533, 0.07049073768502413),
 (534, 0.08451542547285165),
 (535, 0.10968169942141635),
 (536, 0.07644707871564382),
 (537, 0.07049073768502413),
 (538, 0.0),
 (539, 0.26089696604360174),
 (540, 0.0563436169819011),
 (541, 0.06965451903188581),
 (542, 0.04040610178208843),
 (543, 0.08827348295047496),
 (544, 0.060717674071891624),
 (545, 0.028571428571428567),
 (546, 0.06629935441317959),
 (547, 0.08827348295047496),
 (548, 0.0),
 (549, 0.1246111965698067),
 (550, 0.028571428571428567),
 (551, 0.0447773662839645),
 (552, 0.0),
 (553, 0.03253000243161777),
 (554, 0.0),
 (555, 0.0497245158098847),
 (556, 0.028988551782622416),
 (557, 0.1449427589131121),
 (558, 0.0),
 (559, 0.03253000243161777),
 (560, 0.04643634602125721),
 (561, 0.03688555567816587),
 (562, 0.0),
 (563, 0.02742042485535409),
 (564, 0.0994490316197694),
 (565, 0.04600437062282361),
 (566, 0.024655683636076894),
 (567, 0.030358837035945812),
 (568, 0.1449427589131121),
 (569, 0.024397501823713332),
 (570, 0.07559289460184544),
 (571, 0.021821789023599235),
 (572, 0.08656873106996099),
 (573, 0.02258769757263128),
 (574, 0.024397501823713332),
 (575, 0.057142857142857134),
 (576, 0.028988551782622416),
 (577, 0.15430334996209188),
 (578, 0.04829452884162951),
 (579, 0.12344267996967351),
 (580, 0.02519763153394848),
 (581, 0.16574838603294897),
 (582, 0.24397501823713333),
 (583, 0.052164053095730106),
 (584, 0.05096471914376255),
 (585, 0.0),
 (586, 0.045584230583855176),
 (587, 0.07824607964359516),
 (588, 0.028988551782622416),
 (589, 0.09862273454430757),
 (590, 0.035245368842512066),
 (591, 0.07733088933397005),
 (592, 0.027066598098038335),
 (593, 0.0),
 (594, 0.05484084971070818),
 (595, 0.13533299049019168),
 (596, 0.09658905768325902),
 (597, 0.05797710356524483),
 (598, 0.03984095364447979),
 (599, 0.03363839659676322),
 (600, 0.07244179326244427),
 (601, 0.03688555567816587),
 (602, 0.04517539514526256),
 (603, 0.05797710356524483),
 (604, 0.07049073768502413),
 (605, 0.0),
 (606, 0.0),
 (607, 0.06492654830247076),
 (608, 0.0),
 (609, 0.047809144373375745),
 (610, 0.060609152673132646),
 (611, 0.02492223931396134),
 (612, 0.07100716024967263),
 (613, 0.03877833671647406),
 (614, 0.059761430466719674),
 (615, 0.033149677206589796),
 (616, 0.0),
 (617, 0.055577001437672836),
 (618, 0.09862273454430757),
 (619, 0.0),
 (620, 0.0),
 (621, 0.07049073768502413),
 (622, 0.02238868314198225),
 (623, 0.0),
 (624, 0.12298800925361816),
 (625, 0.03194382824999699),
 (626, 0.09258200997725513),
 (627, 0.11633501014942217),
 (628, 0.0),
 (629, 0.04984447862792268),
 (630, 0.02577696311132335),
 (631, 0.02742042485535409),
 (632, 0.08336550215650926),
 (633, 0.023904572186687872),
 (634, 0.08696565534786725),
 (635, 0.07559289460184544),
 (636, 0.028571428571428567),
 (637, 0.052796367734845466),
 (638, 0.036037498507822355),
 (639, 0.0),
 (640, 0.0515539262226467),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10690449676496976),
 (644, 0.05797710356524483),
 (645, 0.047809144373375745),
 (646, 0.055577001437672836),
 (647, 0.052796367734845466),
 (648, 0.03253000243161777),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.024655683636076894),
 (653, 0.12298800925361816),
 (654, 0.089554732567929),
 (655, 0.026082026547865053),
 (656, 0.0),
 (657, 0.037332669647327864),
 (658, 0.05345224838248488),
 (659, 0.027066598098038335),
 (660, 0.10350983390135313),
 (661, 0.17036708399998393),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06506000486323554),
 (665, 0.0791945516022682),
 (666, 0.052164053095730106),
 (667, 0.0),
 (668, 0.07049073768502413),
 (669, 0.036037498507822355),
 (670, 0.017817416127494958),
 (671, 0.05413319619607667),
 (672, 0.05884898863364997),
 (673, 0.023002185311411804),
 (674, 0.07396705090823068),
 (675, 0.0515539262226467),
 (676, 0.033149677206589796),
 (677, 0.027788500718836418),
 (678, 0.06277648205743444),
 (679, 0.0),
 (680, 0.08451542547285165),
 (681, 0.035245368842512066),
 (682, 0.024147264420814756),
 (683, 0.0515539262226467),
 (684, 0.0),
 (685, 0.03779644730092272),
 (686, 0.0),
 (687, 0.11595420713048966),
 (688, 0.05096471914376255),
 (689, 0.0),
 (690, 0.028988551782622416),
 (691, 0.10141851056742199),
 (692, 0.12073632210407378),
 (693, 0.0),
 (694, 0.022792115291927588),
 (695, 0.06900655593423542),
 (696, 0.0),
 (697, 0.0),
 (698, 0.02366905341655754),
 (699, 0.0),
 (700, 0.030860669992418377),
 (701, 0.06506000486323554),
 (702, 0.024397501823713332),
 (703, 0.020965696734438367),
 (704, 0.07396705090823068),
 (705, 0.025482359571881275),
 (706, 0.026082026547865053),
 (707, 0.0),
 (708, 0.025482359571881275),
 (709, 0.0),
 (710, 0.0447773662839645),
 (711, 0.06629935441317959),
 (712, 0.0),
 (713, 0.02742042485535409),
 (714, 0.0),
 (715, 0.1057361065275362),
 (716, 0.035245368842512066),
 (717, 0.0),
 (718, 0.04643634602125721),
 (719, 0.0),
 (720, 0.02742042485535409),
 (721, 0.033149677206589796),
 (722, 0.0),
 (723, 0.02672612419124244),
 (724, 0.02577696311132335),
 (725, 0.0),
 (726, 0.0),
 (727, 0.036454130828824455),
 (728, 0.07559289460184544),
 (729, 0.0),
 (730, 0.019138975058773815),
 (731, 0.05484084971070818),
 (732, 0.0791945516022682),
 (733, 0.0447773662839645),
 (734, 0.05039526306789696),
 (735, 0.04984447862792268),
 (736, 0.033149677206589796),
 (737, 0.08017837257372731),
 (738, 0.0),
 (739, 0.03877833671647406),
 (740, 0.13199091933711365),
 (741, 0.05884898863364997),
 (742, 0.03450327796711771),
 (743, 0.02577696311132335),
 (744, 0.06761234037828133),
 (745, 0.06277648205743444),
 (746, 0.08696565534786725),
 (747, 0.024147264420814756),
 (748, 0.03779644730092272),
 (749, 0.0),
 (750, 0.0515539262226467),
 (751, 0.03779644730092272),

In [135]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(similarity[0])), reverse=True, key= lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [136]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Ender's Game
Aliens vs Predator: Requiem

In [137]:
sorted(list(enumerate(similarity[0])), reverse=True, key= lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1192, 0.2581988897471611),
 (507, 0.25302403842552984),
 (260, 0.25110592822973776),
 (1214, 0.24944382578492943)]